### ISSUE TITLE
Specify versions for dependencies

### ISSUE THREAD

**Issue by wmedrano** [acmcarther/space_coop#18]
`lib = "*"` should be avoided

``` toml
[dependencies]
time = "*"
byteorder = "*"
itertools = "*"
glutin = "0.2.0"
cgmath = "*"
gfx = "*"
gfx_window_glutin = "*"
```
